# Pytorch Download and Install

https://pytorch.org/get-started/locally/

# Data Manipulation


## Getting Started

In [1]:
import torch

Tensors represent (possibly multi-dimensional) arrays of numerical values.
The simplest object we can create is a vector. To start, we can use `arange` to create a row vector with 12 consecutive integers.

In [2]:
x = torch.arange(12, dtype=torch.float64)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
       dtype=torch.float64)

In [3]:
# We can get the tensor shape through the shape attribute.
x.shape

torch.Size([12])

In [4]:
# .shape is an alias for .size(), and was added to more closely match numpy
x.size()

torch.Size([12])

We use the `reshape` function to change the shape of one (possibly multi-dimensional) array, to another that contains the same number of elements.

For example, we can transform the shape of our line vector `x` to (3, 4), which contains the same values but interprets them as a matrix containing 3 rows and 4 columns.

Note that although the shape has changed, the elements in `x` have not.

`reshape` 함수는 하나의 배열의 모양을 다른 모양으로 변경하는 데 사용됩니다. 이때 배열의 총 원소 수는 동일하게 유지됩니다.

예를 들어, 주어진 코드에서는 선 벡터 `x`의 모양을 (3, 4)로 변환하여, 동일한 값들을 가지지만 이 값을 3개의 행과 4개의 열을 가진 행렬로 해석합니다.

모양은 변경되었지만 `x`의 원소 값은 변경되지 않았음에 주의하십시오.

In [5]:
x = x.reshape((3, 2, 2))
x

tensor([[[ 0.,  1.],
         [ 2.,  3.]],

        [[ 4.,  5.],
         [ 6.,  7.]],

        [[ 8.,  9.],
         [10., 11.]]], dtype=torch.float64)

Fortunately, PyTorch can automatically work out one dimension given the other.

We can invoke this capability by placing `-1` for the dimension that we would like PyTorch to automatically infer.

In our case, instead of `x.reshape((3, 4))`, we could have equivalently used `x.reshape((-1, 4))` or `x.reshape((3, -1))`.

다행히 PyTorch는 다른 차원을 주어진 차원을 기반으로 자동으로 계산할 수 있습니다.

이 기능을 사용하려면 PyTorch가 자동으로 추론하도록 차원에 대해 `-1`을 넣으면 됩니다.

우리의 경우 `x.reshape((3, 4))` 대신에 `x.reshape((-1, 4))` 또는 `x.reshape((3, -1))`와 동등하게 사용할 수 있습니다.

In [6]:
x = torch.arange(12, dtype=torch.float64)
x.reshape((-1,4))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=torch.float64)

In [7]:
x = torch.arange(12, dtype=torch.float64)
x.reshape((3,2,-1))

tensor([[[ 0.,  1.],
         [ 2.,  3.]],

        [[ 4.,  5.],
         [ 6.,  7.]],

        [[ 8.,  9.],
         [10., 11.]]], dtype=torch.float64)

In [13]:
x = torch.arange(12, dtype=torch.float64)
x.reshape((3,-1))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=torch.float64)

In [14]:
x=torch.FloatTensor(2, 3)
print(x)
x.dtype

tensor([[0., 0., 0.],
        [0., 0., 0.]])


torch.float32

In [17]:
torch.Tensor(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [16]:
torch.empty(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

<span style="color:red" > Pytorch uses float32 by default for tranining!!!! </span>

torch.Tensor() is just an alias to torch.FloatTensor() which is the default type of tensor, when no dtype is specified during tensor construction.

From the torch for numpy users notes, it seems that torch.Tensor() is a drop-in replacement of numpy.empty()

So, in essence torch.FloatTensor() and torch.empty() does the same job.

The `empty` method just grabs some memory and hands us back a matrix without setting the values of any of its entries. This is `very efficient but it means that the entries might take any arbitrary values`, including very big ones! Typically, we'll want our matrices initialized either with ones, zeros, some known constant or numbers randomly sampled from a known distribution.

Perhaps most often, we want an array of all zeros. To create tensor with all elements set to 0 and a shape of (2, 3, 4) we can invoke:

기본적으로 PyTorch는 훈련에 대해 float32를 사용합니다.

`torch.Tensor()`은 단순히 `torch.FloatTensor()`에 대한 별칭으로, 텐서 생성 중 dtype이 지정되지 않은 경우의 기본 텐서 유형입니다.

Torch for NumPy 사용자 노트에서 보면 `torch.Tensor()`은 `numpy.empty()`의 대체품인 것으로 나와있는데, 이것은 매우 효율적으로 동작하지만, 그 안에 있는 항목의 값을 설정하지 않으므로 임의의 값을 가질 수 있다는 것을 의미합니다. 일반적으로 우리는 행렬을 모두 1, 0, 일정한 상수 또는 알려진 분포에서 무작위로 샘플링된 숫자로 초기화하길 원할 것입니다.

아마도 가장 자주 사용하는 것은 모든 원소가 0인 배열을 원하는 경우일 것입니다. 모든 원소가 0으로 설정되고 (2, 3, 4) 모양을 가진 텐서를 생성하려면 다음을 사용할 수 있습니다:

In [18]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

We can create tensors with each element set to 1 works via

In [19]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

We can also specify the value of each element in the desired NDArray by supplying a Python list containing the numerical values.

In [ ]:
y = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
y

In some cases, we will want to randomly sample the values of each element in the tensor according to some known probability distribution. This is especially common when we intend to use the tensor as a parameter in a neural network. The following snippet creates an tensor with a shape of (3,4). Each of its elements is randomly sampled in a normal distribution with zero mean and unit variance.

In [ ]:
torch.randn(3, 4)

## 연산

자주 발생하는 상황 중 하나는 배열에 함수를 적용하려고 하는 경우입니다. 가장 간단하면서 가장 유용한 함수 중 일부는 원소별 함수입니다. 이러한 함수는 두 개의 배열의 해당 원소에 단일 스칼라 연산을 수행하여 작동합니다. 스칼라에서 스칼라로 매핑하는 함수로부터 원소별 함수를 만들 수 있습니다. 수학적 표기법에서는 이러한 함수를 $f: \mathbb{R} \rightarrow \mathbb{R}$로 나타냅니다. 동일한 모양의 두 벡터 $\mathbf{u}$ 및 $\mathbf{v}$와 함수 $f$가 주어진 경우, 모든 $i$에 대해 $c_i \gets f(u_i, v_i)$로 설정하여 벡터 $\mathbf{c} = F(\mathbf{u},\mathbf{v})$를 생성할 수 있습니다. 여기서 스칼라 함수를 원소별 벡터 작업으로 *업그레이드*하여 벡터 값 함수 $F: \mathbb{R}^d \rightarrow \mathbb{R}^d$를 생성했습니다. PyTorch에서는 공통 표준 산술 연산자 (+, -, /, *, **)가 임의 모양의 동일한 모양의 텐서에 대한 원소별 작업으로 *업그레이드*되었습니다. 행렬을 포함한 동일한 모양의 두 텐서에 대해 어떤 두 텐서에 대한 원소별 작업을 호출할 수 있습니다.

In [7]:
x = torch.tensor([1, 2, 4, 8], dtype=torch.float32)
y = torch.ones_like(x) * 2
print('x =', x)
print('x + y', x + y)
print('x - y', x - y)
print('x * y', x * y)
print('x / y', x / y)

x = tensor([1., 2., 4., 8.])
x + y tensor([ 3.,  4.,  6., 10.])
x - y tensor([-1.,  0.,  2.,  6.])
x * y tensor([ 2.,  4.,  8., 16.])
x / y tensor([0.5000, 1.0000, 2.0000, 4.0000])


Many more operations can be applied element-wise, such as exponentiation:

In [8]:
torch.exp(x)
# Note: torch.exp is not implemented for 'torch.LongTensor'.

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In addition to computations by element, we can also perform matrix operations, like matrix multiplication using the `mm` or `matmul` function. Next, we will perform matrix multiplication of `x` and the transpose of `y`. We define `x` as a matrix of 3 rows and 4 columns, and `y` is transposed into a matrix of 4 rows and 3 columns. The two matrices are multiplied to obtain a matrix of 3 rows and 3 columns.

In [3]:
import torch

# 0에서 11까지의 수로 이루어진 1차원 텐서를 생성하고 이를 3x4 형태의 2차원 텐서로 변형합니다.
x = torch.arange(12, dtype=torch.float32).reshape((3, 4))

# 3x4 형태의 텐서를 직접 지정하여 초기화합니다.
# 데이터 유형은 float32로 설정합니다.
y = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]], dtype=torch.float32)

# x의 데이터 유형을 출력합니다 (float32).
print(x.dtype)

# x 텐서의 내용을 출력합니다.
print(x)

# y 텐서를 전치하여 출력합니다 (행과 열을 바꿉니다).
print(y.t())

# x와 y의 행렬 곱을 계산하고 결과를 출력합니다.
# 여기서 '*' 연산자는 행렬 곱이 아니라 원소별 곱입니다.
# 따라서 .mm() 또는 .matmul() 함수를 사용하여 행렬 곱을 수행합니다.
# 결과는 3x3 텐서입니다.
print(torch.mm(x, y.t()))

# 또 다른 방법으로 행렬 곱을 수행합니다.
print(torch.matmul(x, y.t()))

torch.float32
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[2., 1., 4.],
        [1., 2., 3.],
        [4., 3., 2.],
        [3., 4., 1.]])
tensor([[ 18.,  20.,  10.],
        [ 58.,  60.,  50.],
        [ 98., 100.,  90.]])
tensor([[ 18.,  20.,  10.],
        [ 58.,  60.,  50.],
        [ 98., 100.,  90.]])


In [19]:
print(y)
print((y).shape)

tensor([[1., 2., 3., 4.],
        [4., 3., 2., 1.],
        [4., 3., 2., 1.]])
torch.Size([3, 4])


In [20]:
print(y.t())
print((y.t()).shape)

tensor([[1., 4., 4.],
        [2., 3., 3.],
        [3., 2., 2.],
        [4., 1., 1.]])
torch.Size([4, 3])


In [6]:
y.shape

torch.Size([3, 4])

In [21]:
print((x*y).shape)

torch.Size([3, 4])


In [66]:
s = torch.tensor([[60, 30, 10, 30], [10, 20, 30, 40], [40, 30, 20, 10], [40, 30, 20, 10],[40, 30, 20, 10]], dtype=torch.float32)
weight = torch.tensor([[0.3, 0.3, 0.2, 0.2]], dtype=torch.float32)
print(torch.mm(s, weight.t()))

tensor([[35.],
        [23.],
        [27.],
        [27.],
        [27.]])


Note that `torch.dot() behaves differently to np.dot()`. There's been some discussion about what would be desirable here. Specifically, `torch.dot() treats both a and b as 1D vectors` (irrespective of their original shape) and computes their `inner product`. 

In [ ]:
import numpy as np
x = torch.arange(12, dtype=torch.float32).reshape((3,4))
y = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]], dtype=torch.float32)
print("np.dot:")
print(np.dot(x,y.t()))

x = torch.flatten(x)
y = torch.flatten(y)
x.shape, y.shape
print(f"torch.dot:{torch.dot(x,y)}")

np.dot:
[[ 18.  20.  10.]
 [ 58.  60.  50.]
 [ 98. 100.  90.]]
torch.dot:168.0


In [ ]:
import numpy as np
# numpy와 torch를 import합니다.

x = torch.arange(12, dtype=torch.float32).reshape((3,4))
# torch.arange를 사용하여 0에서 11까지의 값을 생성하고 dtype을 float32로 설정한 후 (3,4) 모양의 텐서로 변환합니다.
# 결과적으로 x는 다음과 같이 생겼습니다:
# tensor([[ 0.,  1.,  2.,  3.],
#         [ 4.,  5.,  6.,  7.],
#         [ 8.,  9., 10., 11.]])

y = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]], dtype=torch.float32)
# 주어진 리스트를 사용하여 torch.tensor를 생성하고 dtype을 float32로 설정합니다.
# 결과적으로 y는 다음과 같이 생겼습니다:
# tensor([[2., 1., 4., 3.],
#         [1., 2., 3., 4.],
#         [4., 3., 2., 1.]])

print("np.dot:")
# "np.dot:" 문자열을 출력합니다.

# 아래에서는 numpy의 dot 함수를 사용하여 두 텐서의 내적을 계산하고 출력합니다.
print(np.dot(x, y.t()))
# x와 y의 전치(transpose)를 내적합니다. numpy의 dot 함수는 내적을 수행하는 함수입니다.
# 결과는 다음과 같이 계산됩니다:
# array([[ 18.,  20.,  10.],
#        [ 58.,  60.,  50.],
#        [ 98., 100.,  90.]])
# 결과는 3x3 크기의 numpy 배열입니다.

x = torch.flatten(x)
# x를 1차원 텐서로 평평하게(flatten) 합니다.
# 결과적으로 x는 다음과 같이 생겼습니다: tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])
y = torch.flatten(y)
# y도 마찬가지로 1차원 텐서로 평평하게(flatten) 합니다.
# 결과적으로 y는 다음과 같이 생겼습니다: tensor([2., 1., 4., 3., 1., 2., 3., 4., 4., 3., 2., 1.])

x.shape, y.shape
# x와 y의 모양(shape)을 출력합니다.

print(f"torch.dot: {torch.dot(x, y)}")
# torch.dot 함수를 사용하여 두 1차원 텐서 x와 y의 내적을 계산하고 출력합니다.
# 결과는 내적 값이 출력됩니다.


In [35]:
import torch
import numpy as np

# 두 1x3 형태의 텐서를 생성합니다. 데이터 유형은 float32로 설정합니다.
x = torch.tensor([[1, 2, 3]], dtype=torch.float32)
y = torch.tensor([[0, 1, 2]], dtype=torch.float32)

# NumPy의 np.dot() 함수를 사용하여 두 텐서의 내적을 계산하고 결과를 출력합니다.
# 내적은 두 벡터의 요소별 곱셈의 합입니다.
# 결과는 스칼라 값입니다.
print(np.dot(x, y.t()))


[[8.]]


We can also merge multiple tensors. For that, we need to tell the system along which dimension to merge. The example below merges two matrices along dimension 0 (along rows) and dimension 1 (along columns) respectively.

In [61]:
x = torch.arange(12, dtype=torch.float32).reshape((3,4))
y = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]], dtype=torch.float32)
z=torch.cat((x, y), dim=0)
print(z)
print(z.shape)
z=torch.cat((x, y), dim=1)
print(z)
print(z.shape)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])
torch.Size([6, 4])
tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])
torch.Size([3, 8])


In [ ]:
x = torch.arange(12, dtype=torch.float32).reshape((3,4))
# 0에서 11까지의 값을 가지는 3x4 모양의 torch 텐서 x를 생성합니다.
# 결과적으로 x는 다음과 같이 생겼습니다:
# tensor([[ 0.,  1.,  2.,  3.],
#         [ 4.,  5.,  6.,  7.],
#         [ 8.,  9., 10., 11.]])

y = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]], dtype=torch.float32)
# 주어진 리스트를 사용하여 torch 텐서 y를 생성합니다.
# 결과적으로 y는 다음과 같이 생겼습니다:
# tensor([[2., 1., 4., 3.],
#         [1., 2., 3., 4.],
#         [4., 3., 2., 1.])

z = torch.cat((x, y), dim=0)
# torch.cat 함수를 사용하여 x와 y를 수직 방향(dim=0)으로 연결합니다.
# 결과적으로 z는 x와 y를 수직으로 연결한 6x4 모양의 텐서입니다.
# 행의 수가 증가하므로 x와 y의 열 수는 동일해야 합니다.
# 결과는 다음과 같이 생겼습니다:
# tensor([[ 0.,  1.,  2.,  3.],
#         [ 4.,  5.,  6.,  7.],
#         [ 8.,  9., 10., 11.],
#         [ 2.,  1.,  4.,  3.],
#         [ 1.,  2.,  3.,  4.],
#         [ 4.,  3.,  2.,  1.]])

print(z)
# z를 출력합니다.
print(z.shape)
# z의 모양(shape)을 출력합니다. 결과는 (6, 4)입니다.

z = torch.cat((x, y), dim=1)
# torch.cat 함수를 사용하여 x와 y를 수평 방향(dim=1)으로 연결합니다.
# 결과적으로 z는 x와 y를 수평으로 연결한 3x8 모양의 텐서입니다.
# 열의 수가 증가하므로 x와 y의 행 수는 동일해야 합니다.
# 결과는 다음과 같이 생겼습니다:
# tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
#         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
#         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

print(z)
# z를 출력합니다.
print(z.shape)
# z의 모양(shape)을 출력합니다. 결과는 (3, 8)입니다.


In [59]:
x = torch.arange(12, dtype=torch.float32).reshape((3,4))
y = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4]], dtype=torch.float32)
print(x)
print(x.shape,"\n")

print(y)
print(y.shape,"\n")

z=torch.cat((x, y), dim=0)
print(z)
print(z.shape,"\n")

z=torch.cat((x, y), dim=1)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
torch.Size([3, 4]) 

tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.]])
torch.Size([2, 4]) 

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.]])
torch.Size([5, 4]) 



RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 3 but got size 2 for tensor number 1 in the list.

Sometimes, we may want to construct binary tensors via logical statements. Take `x == y` as an example. If `x` and `y` are equal for some entry, the new tensor has a value of 1 at the same position; otherwise it is 0.

In [62]:
x == y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [64]:
print(x==y)
z=y
print(z==y)

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Summing all the elements in the tensor yields an tensor with only one element.

In [37]:
x.sum()

tensor(66.)

In [70]:
s.sum(dim=1)

tensor([130., 100., 100., 100., 100.])

In [71]:
s.sum(dim=0)

tensor([190., 140., 100., 100.])

In [12]:
x = x.reshape(3,4)
print(x)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


We can transform the result into a scalar in Python using the `a.item()`. In the following example, the $\ell_2$ norm of `x` yields a single element tensor. `The final result is transformed into a scalar`.

In [42]:
import numpy as np
print( x.norm().item() )

22.494443893432617


## Broadcast Mechanism

In the above section, we saw how to perform operations on two tensors of the same shape. When their shapes differ, a broadcasting mechanism may be triggered analogous to NumPy: first, copy the elements appropriately so that the two tensors have the same shape, and then carry out operations by element.

In [43]:
a = torch.arange(3, dtype=torch.float).reshape((3, 1))
b = torch.arange(2, dtype=torch.float).reshape((1, 2))
a, b

(tensor([[0.],
         [1.],
         [2.]]),
 tensor([[0., 1.]]))

Since `a` and `b` are (3x1) and (1x2) matrices respectively, their shapes do not match up if we want to add them. PyTorch addresses this by 'broadcasting' the entries of both matrices into a larger (3x2) matrix as follows: for matrix `a` it replicates the columns, for matrix `b` it replicates the rows before adding up both element-wise.

In [44]:
a + b

tensor([[0., 1.],
        [1., 2.],
        [2., 3.]])

## Indexing and Slicing

Just like in any other Python array, elements in a tensor can be accessed by its index. In good Python tradition the first element has index 0 and ranges are specified to include the first but not the last element. By this logic `1:3` selects the second and third element. Let's try this out by selecting the respective rows in a matrix.

In [ ]:
x[1:3]

Beyond reading, we can also write elements of a matrix.

In [ ]:
x[1, 2] = 9
x

If we want to assign multiple elements the same value, we simply index all of them and then assign them the value. For instance, `[0:2, :]` accesses the first and second rows. While we discussed indexing for matrices, this obviously also works for vectors and for tensors of more than 2 dimensions.

In [ ]:
x[0:2, :] = 12
x

## Saving Memory

In the previous example, every time we ran an operation, we allocated new memory to host its results.

For example, if we write `y = x + y`, we will dereference the matrix that `y` used to point to and instead point it at the newly allocated memory.

In the following example we demonstrate this with Python's `id()` function, which gives us the exact address of the referenced object in memory.

After running `y = y + x`, we will find that `id(y)` points to a different location.

That is because Python first evaluates `y + x`, allocating new memory for the result and then subsequently redirects `y` to point at this new location in memory.

In [45]:
before = id(y)
y = y + x
id(y) == before

False

This might be undesirable for two reasons. First, we do not want to run around allocating memory unnecessarily all the time. In machine learning, we might have hundreds of megabytes of parameters and update all of them multiple times per second. Typically, we will want to perform these updates *in place*. Second, we might point at the same parameters from multiple variables. If we do not update in place, this could cause a memory leak, making it possible for us to inadvertently reference stale parameters.

Fortunately, performing in-place operations in PyTorch is easy. We can assign the result of an operation to a previously allocated array with slice notation, e.g., `y[:] = <expression>`. To illustrate the behavior, we first clone the shape of a matrix using `zeros_like` to allocate a block of 0 entries.

이것은 두 가지 이유로 바람직하지 않을 수 있습니다. 첫째, 우리는 메모리를 불필요하게 할당하고 다니길 원하지 않습니다. 기계 학습에서는 수백 메가바이트의 매개 변수를 가지고 있을 수 있으며 이러한 매개 변수를 초당 여러 번 업데이트하고 싶을 것입니다. 일반적으로 우리는 이러한 업데이트를 *in place*에서 수행하려고 합니다. 둘째, 동일한 매개 변수를 여러 변수에서 가리킬 수 있습니다. 우리가 *in place*로 업데이트하지 않으면 이것은 메모리 누수를 발생시킬 수 있으며 우리가 잘못된 매개 변수를 참조하게 만들 수 있습니다.

다행스럽게도, PyTorch에서 *in-place* 연산을 수행하는 것은 쉽습니다. 우리는 슬라이스 표기법을 사용하여 이미 할당된 배열에 연산의 결과를 할당할 수 있습니다. 예를 들어, `y[:] = <expression>`와 같이 표현할 수 있습니다. 이 동작을 설명하기 위해 먼저 `zeros_like`를 사용하여 행렬의 모양을 복제하여 0 항목의 블록을 할당합니다.

In [ ]:
z = torch.zeros_like(y)
print('id(z):', id(z))
z[:] = x + y
print('id(z):', id(z))

While this looks pretty, `x+y` here will still allocate a temporary buffer to store the result of `x+y` before copying it to `z[:]`. To make even better use of memory, we can directly invoke the underlying `tensor` operation, in this case `add`, avoiding temporary buffers. We do this by specifying the `out` keyword argument, which every `tensor` operator supports:

In [ ]:
before = id(z)
torch.add(x, y, out=z)
id(z) == before

If the value of `x ` is not reused in subsequent computations, we can also use `x[:] = x + y` or `x += y` to reduce the memory overhead of the operation.

In [ ]:
before = id(x)
x += y
id(x) == before

## `Mutual Transformation of PyTorch and NumPy`

Converting PyTorch Tensors to and from NumPy Arrays is easy.

The converted arrays do *not* share memory.

This minor inconvenience is actually quite important: when you perform operations on the CPU or one of the GPUs, you do not want PyTorch having to wait whether NumPy might want to be doing something else with the same chunk of memory. `.tensor` and `.numpy` do the trick.

In [13]:
a = x.numpy()
print(type(a))
b = torch.tensor(a)
print(type(b))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>


# <span style="color:yellow"> Pytorch Tutorial </span>

https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html