# Regression Using Linear Neural Network

## Mango and orange production for given environmental data
<img src='img/linear_regression_table.jpg' width="800">

Mangoes = $w_{11}$ * temp + $w_{21}$ * rainfall + $w_{31}$ * humidity + $b_1$ 

Oranges = $w_{12}$ * temp + $w_{22}$ * rainfall + $w_{32}$ * humidity + $b_2$

$
\begin{bmatrix}
\text{Mangoes} ~\text{Oranges}
\end{bmatrix} =
\begin{bmatrix}
\text{temp} &\text{Rainfall} &\text{Humidity}\\
\end{bmatrix}
\begin{bmatrix}
w_{11} &w_{12}\\
w_{21} &w_{22}\\
w_{31} &w_{32}
\end{bmatrix} + 
\begin{bmatrix}
b_1~b_2
\end{bmatrix} 
$

## Data preparation

In [1]:
import torch
import numpy as np
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

#inputs = torch.tensor(inputs, dtype=torch.float32)
#targets = torch.tensor(targets, dtype=torch.float32)




## Dataset

In [2]:
from torch.utils.data import TensorDataset

dataset = TensorDataset(inputs, targets) #tuple of inputs and targets

## Dataloading

In [3]:
from torch.utils.data import DataLoader

batch_size = 5
train_loader = DataLoader(dataset, batch_size=batch_size, shuffle=True)

# Batch Sampling
for input,target in train_loader:
    print(input)
    print(target)
    break


tensor([[ 68.,  97.,  70.],
        [ 87., 134.,  58.],
        [ 74.,  66.,  43.],
        [ 68.,  96.,  71.],
        [101.,  44.,  37.]])
tensor([[102., 120.],
        [119., 133.],
        [ 57.,  69.],
        [104., 118.],
        [ 21.,  38.]])


## Design a neural network

In [4]:
# Linear Regression Model
from torch import nn
class linearRegression(nn.Module):
    def __init__(self):
        super().__init__()
        self.norm = nn.BatchNorm1d(3)
        self.linear = nn.Linear(3, 2)  # input and output is 1 dimension
    def forward(self, x):
        x = self.norm(x)
        out = self.linear(x)
        return out

model = linearRegression()
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=1e-3)


## Training

In [5]:

num_epochs = 1000
for epoch in range(num_epochs):    
    for input, target in train_loader:
        pred = model(input)
        loss = criterion(pred, target)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        print(f'Epoch[{epoch+1}/{num_epochs}], loss: {loss.item():.6f}')



for name, param in model.named_parameters():
    print (name, param.data.numpy(), end=' ')


Epoch[1/1000], loss: 4454.614746
Epoch[1/1000], loss: 7482.545410
Epoch[1/1000], loss: 12881.191406
Epoch[2/1000], loss: 8399.397461
Epoch[2/1000], loss: 11824.992188
Epoch[2/1000], loss: 4351.441895
Epoch[3/1000], loss: 7450.496094
Epoch[3/1000], loss: 10231.369141
Epoch[3/1000], loss: 6565.999023
Epoch[4/1000], loss: 7913.678223
Epoch[4/1000], loss: 10222.268555
Epoch[4/1000], loss: 5638.862305
Epoch[5/1000], loss: 9410.413086
Epoch[5/1000], loss: 5387.826660
Epoch[5/1000], loss: 8157.177246
Epoch[6/1000], loss: 8094.217285
Epoch[6/1000], loss: 9424.701172
Epoch[6/1000], loss: 4050.330566
Epoch[7/1000], loss: 9463.589844
Epoch[7/1000], loss: 5018.415039
Epoch[7/1000], loss: 4724.540039
Epoch[8/1000], loss: 7553.636719
Epoch[8/1000], loss: 2814.241699
Epoch[8/1000], loss: 5209.043945
Epoch[9/1000], loss: 5116.786133
Epoch[9/1000], loss: 5487.731445
Epoch[9/1000], loss: 612.451660
Epoch[10/1000], loss: 4552.588379
Epoch[10/1000], loss: 594.308777
Epoch[10/1000], loss: 1578.441772
Epoch

## Evaluation

In [6]:
model.eval()
preds = model(inputs)
print("Prediction: \n",preds)
print("Actual targets:\n",targets)


Prediction: 
 tensor([[ 59.7900,  74.7877],
        [ 81.0910,  97.6775],
        [114.4632, 127.7436],
        [ 29.1039,  40.9511],
        [ 97.3071, 117.1375],
        [ 58.7075,  73.6510],
        [ 80.8453,  97.7039],
        [114.6665, 128.0598],
        [ 30.1865,  42.0879],
        [ 98.1440, 118.3007],
        [ 59.5443,  74.8141],
        [ 80.0084,  96.5407],
        [114.7089, 127.7172],
        [ 28.2671,  39.7880],
        [ 98.3897, 118.2743]], grad_fn=<AddmmBackward0>)
Actual targets:
 tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])


## Prediction

If (temp, rain, humidity) is given as (80, 60, 50), the mangoes and oranges are predicted by

In [7]:
x=torch.tensor([[80, 60, 50]], dtype=torch.float32)
pred = model(x)
print("Prediction: \n",pred.data)

print(f"Magones:{pred.data[0][0]:.1f} tons, and Oranges:{pred.data[0][1]:.1f} tons")


Prediction: 
 tensor([[55.8527, 72.0084]])
Magones:55.9 tons, and Oranges:72.0 tons
